import { docsType } from "../types"

const FAKE_DATA: docsType = {
    articles: [
        {
            _id: JSON.parse('1'),
            image: {key: 'none'},
            name: 'Title 1',
            role: 'general',
            source: 'anonymous',
            story: 'lorem',
            isApproved: true,
        },
        {
            _id: JSON.parse('2'),
            image: {key: 'none'},
            name: 'Title 2',
            role: 'general',
            source: 'anonymous',
            story: 'lorem',
            isApproved: true,
        },
        {
            _id: JSON.parse('3'),
            image: {key: 'none'},
            name: 'Title 3',
            role: 'general',
            source: 'anonymous',
            story: 'lorem',
            isApproved: true,
        },
        {
            _id: JSON.parse('4'),
            image: {key: 'none'},
            name: 'Title 4',
            role: 'general',
            source: 'anonymous',
            story: 'lorem',
            isApproved: true,
        },
        {
            _id: JSON.parse('5'),
            image: {key: 'none'},
            name: 'Title 5',
            role: 'general',
            source: 'anonymous',
            story: 'lorem',
            isApproved: true,
        },
        {
            _id: JSON.parse('6'),
            image: {key: 'none'},
            name: 'Title 6',
            role: 'general',
            source: 'anonymous',
            story: 'lorem',
            isApproved: true,
        },
        {
            _id: JSON.parse('7'),
            image: {key: 'none'},
            name: 'Title 7',
            role: 'general',
            source: 'anonymous',
            story: 'lorem',
            isApproved: true,
        },
        {
            _id: JSON.parse('8'),
            image: {key: 'none'},
            name: 'Title 8',
            role: 'general',
            source: 'anonymous',
            story: 'lorem',
            isApproved: true,
        },
        {
            _id: JSON.parse('9'),
            image: {key: 'none'},
            name: 'Title 9',
            role: 'general',
            source: 'anonymous',
            story: 'lorem',
            isApproved: true,
        },
        {
            _id: JSON.parse('10'),
            image: {key: 'none'},
            name: 'Title 10',
            role: 'general',
            source: 'anonymous',
            story: 'lorem',
            isApproved: true,
        },
        {
            _id: JSON.parse('11'),
            image: {key: 'none'},
            name: 'Title 11',
            role: 'general',
            source: 'anonymous',
            story: 'lorem',
            isApproved: true,
        },
        {
            _id: JSON.parse('12'),
            image: {key: 'none'},
            name: 'Title 12',
            role: 'general',
            source: 'anonymous',
            story: 'lorem',
            isApproved: true,
        },
        {
            _id: JSON.parse('13'),
            image: {key: 'none'},
            name: 'Title 13',
            role: 'general',
            source: 'anonymous',
            story: 'lorem',
            isApproved: true,
        },
        {
            _id: JSON.parse('14'),
            image: {key: 'none'},
            name: 'Title 14',
            role: 'general',
            source: 'anonymous',
            story: 'lorem',
            isApproved: true,
        },
        {
            _id: JSON.parse('15'),
            image: {key: 'none'},
            name: 'Title 15',
            role: 'general',
            source: 'anonymous',
            story: 'lorem',
            isApproved: true,
        },
        {
            _id: JSON.parse('16'),
            image: {key: 'none'},
            name: 'Title 16',
            role: 'general',
            source: 'anonymous',
            story: 'lorem',
            isApproved: true,
        },
        {
            _id: JSON.parse('17'),
            image: {key: 'none'},
            name: 'Title 17',
            role: 'general',
            source: 'anonymous',
            story: 'lorem',
            isApproved: true,
        },
        {
            _id: JSON.parse('18'),
            image: {key: 'none'},
            name: 'Title 18',
            role: 'general',
            source: 'anonymous',
            story: 'lorem',
            isApproved: true,
        },
        {
            _id: JSON.parse('19'),
            image: {key: 'none'},
            name: 'Title 19',
            role: 'general',
            source: 'anonymous',
            story: 'lorem',
            isApproved: true,
        },
        {
            _id: JSON.parse('20'),
            image: {key: 'none'},
            name: 'Title 20',
            role: 'general',
            source: 'anonymous',
            story: 'lorem',
            isApproved: true,
        },
        {
            _id: JSON.parse('21'),
            image: {key: 'none'},
            name: 'Title 1',
            role: 'general',
            source: 'anonymous',
            story: 'lorem',
            isApproved: true,
        },
        {
            _id: JSON.parse('21'),
            image: {key: 'none'},
            name: 'Title 1',
            role: 'general',
            source: 'anonymous',
            story: 'lorem',
            isApproved: true,
        },
        {
            _id: JSON.parse('22'),
            image: {key: 'none'},
            name: 'Title 22',
            role: 'general',
            source: 'anonymous',
            story: 'lorem',
            isApproved: true,
        },
        {
            _id: JSON.parse('23'),
            image: {key: 'none'},
            name: 'Title 23',
            role: 'general',
            source: 'anonymous',
            story: 'lorem',
            isApproved: false,
        },
        {
            _id: JSON.parse('24'),
            image: {key: 'none'},
            name: 'Title 24',
            role: 'general',
            source: 'anonymous',
            story: 'lorem',
            isApproved: false,
        },
        {
            _id: JSON.parse('25'),
            image: {key: 'none'},
            name: 'Title 25',
            role: 'general',
            source: 'anonymous',
            story: 'lorem',
            isApproved: false,
        },
    ],
    biographies: [
        {
            _id: JSON.parse('1'),
            image: {key: 'bio-image/1648589427678_Abraham Kuyper.jfif'},
            name: 'Abraham Kuyper',
            gender: 'male',
            role: 'Prime Minister',
            birthYear: 1837,
            deathYear: 1920,
            source: 'britannica.com',
            story: 'lorem',
            isApproved: true,
        },
        {
            _id: JSON.parse('2'),
            image: {key: 'bio-image/1648998750383_Anne Bradstreet.jfif'},
            name: 'Anne Bradstreet',
            gender: 'female',
            role: 'Poet',
            birthYear: 1612,
            deathYear: 1672,
            source: 'poetryfoundation.org',
            story: 'lorem',
            isApproved: true,
        },
        {
            _id: JSON.parse('3'),
            image: {key: 'bio-image/1648659558894_C.S. Lewis.jpg'},
            name: 'C.S. Lewis',
            gender: 'male',
            role: 'British writer',
            birthYear: 1898,
            deathYear: 1963,
            source: 'biography.com',
            story: 'lorem',
            isApproved: true,
        },
        {
            _id: JSON.parse('4'),
            image: {key: 'bio-image/1648589427678_Abraham Kuyper.jfif'},
            name: 'Abraham Kuyper',
            gender: 'male',
            role: 'Prime Minister',
            birthYear: 1837,
            deathYear: 1920,
            source: 'britannica.com',
            story: 'lorem',
            isApproved: true,
        },
        {
            _id: JSON.parse('5'),
            image: {key: 'bio-image/1648998750383_Anne Bradstreet.jfif'},
            name: 'Anne Bradstreet',
            gender: 'female',
            role: 'Poet',
            birthYear: 1612,
            deathYear: 1672,
            source: 'poetryfoundation.org',
            story: 'lorem',
            isApproved: true,
        },
        {
            _id: JSON.parse('6'),
            image: {key: 'bio-image/1648659558894_C.S. Lewis.jpg'},
            name: 'C.S. Lewis',
            gender: 'male',
            role: 'British writer',
            birthYear: 1898,
            deathYear: 1963,
            source: 'biography.com',
            story: 'lorem',
            isApproved: true,
        },
        {
            _id: JSON.parse('7'),
            image: {key: 'bio-image/1648589427678_Abraham Kuyper.jfif'},
            name: 'Abraham Kuyper',
            gender: 'male',
            role: 'Prime Minister',
            birthYear: 1837,
            deathYear: 1920,
            source: 'britannica.com',
            story: 'lorem',
            isApproved: true,
        },
        {
            _id: JSON.parse('8'),
            image: {key: 'bio-image/1648998750383_Anne Bradstreet.jfif'},
            name: 'Anne Bradstreet',
            gender: 'female',
            role: 'Poet',
            birthYear: 1612,
            deathYear: 1672,
            source: 'poetryfoundation.org',
            story: 'lorem',
            isApproved: true,
        },
        {
            _id: JSON.parse('9'),
            image: {key: 'bio-image/1648659558894_C.S. Lewis.jpg'},
            name: 'C.S. Lewis',
            gender: 'male',
            role: 'British writer',
            birthYear: 1898,
            deathYear: 1963,
            source: 'biography.com',
            story: 'lorem',
            isApproved: true,
        },
        {
            _id: JSON.parse('10'),
            image: {key: 'bio-image/1648589427678_Abraham Kuyper.jfif'},
            name: 'Abraham Kuyper',
            gender: 'male',
            role: 'Prime Minister',
            birthYear: 1837,
            deathYear: 1920,
            source: 'britannica.com',
            story: 'lorem',
            isApproved: true,
        },
        {
            _id: JSON.parse('11'),
            image: {key: 'bio-image/1648998750383_Anne Bradstreet.jfif'},
            name: 'Anne Bradstreet',
            gender: 'female',
            role: 'Poet',
            birthYear: 1612,
            deathYear: 1672,
            source: 'poetryfoundation.org',
            story: 'lorem',
            isApproved: true,
        },
        {
            _id: JSON.parse('12'),
            image: {key: 'bio-image/1648659558894_C.S. Lewis.jpg'},
            name: 'C.S. Lewis',
            gender: 'male',
            role: 'British writer',
            birthYear: 1898,
            deathYear: 1963,
            source: 'biography.com',
            story: 'lorem',
            isApproved: true,
        },
        {
            _id: JSON.parse('13'),
            image: {key: 'bio-image/1648589427678_Abraham Kuyper.jfif'},
            name: 'Abraham Kuyper',
            gender: 'male',
            role: 'Prime Minister',
            birthYear: 1837,
            deathYear: 1920,
            source: 'britannica.com',
            story: 'lorem',
            isApproved: true,
        },
        {
            _id: JSON.parse('14'),
            image: {key: 'bio-image/1648998750383_Anne Bradstreet.jfif'},
            name: 'Anne Bradstreet',
            gender: 'female',
            role: 'Poet',
            birthYear: 1612,
            deathYear: 1672,
            source: 'poetryfoundation.org',
            story: 'lorem',
            isApproved: true,
        },
        {
            _id: JSON.parse('15'),
            image: {key: 'bio-image/1648659558894_C.S. Lewis.jpg'},
            name: 'C.S. Lewis',
            gender: 'male',
            role: 'British writer',
            birthYear: 1898,
            deathYear: 1963,
            source: 'biography.com',
            story: 'lorem',
            isApproved: true,
        },
        {
            _id: JSON.parse('16'),
            image: {key: 'bio-image/1648589427678_Abraham Kuyper.jfif'},
            name: 'Abraham Kuyper',
            gender: 'male',
            role: 'Prime Minister',
            birthYear: 1837,
            deathYear: 1920,
            source: 'britannica.com',
            story: 'lorem',
            isApproved: true,
        },
        {
            _id: JSON.parse('17'),
            image: {key: 'bio-image/1648998750383_Anne Bradstreet.jfif'},
            name: 'Anne Bradstreet',
            gender: 'female',
            role: 'Poet',
            birthYear: 1612,
            deathYear: 1672,
            source: 'poetryfoundation.org',
            story: 'lorem',
            isApproved: true,
        },
        {
            _id: JSON.parse('18'),
            image: {key: 'bio-image/1648659558894_C.S. Lewis.jpg'},
            name: 'C.S. Lewis',
            gender: 'male',
            role: 'British writer',
            birthYear: 1898,
            deathYear: 1963,
            source: 'biography.com',
            story: 'lorem',
            isApproved: true,
        },
        {
            _id: JSON.parse('19'),
            image: {key: 'bio-image/1648589427678_Abraham Kuyper.jfif'},
            name: 'Abraham Kuyper',
            gender: 'male',
            role: 'Prime Minister',
            birthYear: 1837,
            deathYear: 1920,
            source: 'britannica.com',
            story: 'lorem',
            isApproved: true,
        },
        {
            _id: JSON.parse('20'),
            image: {key: 'bio-image/1648998750383_Anne Bradstreet.jfif'},
            name: 'Anne Bradstreet',
            gender: 'female',
            role: 'Poet',
            birthYear: 1612,
            deathYear: 1672,
            source: 'poetryfoundation.org',
            story: 'lorem',
            isApproved: true,
        },
        {
            _id: JSON.parse('21'),
            image: {key: 'bio-image/1648659558894_C.S. Lewis.jpg'},
            name: 'C.S. Lewis',
            gender: 'male',
            role: 'British writer',
            birthYear: 1898,
            deathYear: 1963,
            source: 'biography.com',
            story: 'lorem',
            isApproved: true,
        },
        {
            _id: JSON.parse('22'),
            image: {key: 'bio-image/1648589427678_Abraham Kuyper.jfif'},
            name: 'Abraham Kuyper',
            gender: 'male',
            role: 'Prime Minister',
            birthYear: 1837,
            deathYear: 1920,
            source: 'britannica.com',
            story: 'lorem',
            isApproved: true,
        },
        {
            _id: JSON.parse('23'),
            image: {key: 'bio-image/1648998750383_Anne Bradstreet.jfif'},
            name: 'Anne Bradstreet',
            gender: 'female',
            role: 'Poet',
            birthYear: 1612,
            deathYear: 1672,
            source: 'poetryfoundation.org',
            story: 'lorem',
            isApproved: true,
        },
        {
            _id: JSON.parse('24'),
            image: {key: 'bio-image/1648659558894_C.S. Lewis.jpg'},
            name: 'C.S. Lewis',
            gender: 'male',
            role: 'British writer',
            birthYear: 1898,
            deathYear: 1963,
            source: 'biography.com',
            story: 'lorem',
            isApproved: true,
        },
    ],
    books: [
        {
            _id: JSON.parse('1'),
            image: {key: 'book-img/1650223048425_100 Ways to Simplify Your Life - Joyce Meyer.jpg'},
            title: '100 Ways to Simplify Your Life',
            author: 'Joyce Meyer',
            filetype: 'pdf',
            document: {key: 'book/1650063214134_100 Ways to Simplify Your Life - Joyce Meyer.pdf', size: 649000},
            isApproved: true,
        },
        {
            _id: JSON.parse('2'),
            image: {key: 'book-img/1650223030084_50_Mindful_Steps_to_Self_Esteem_Everyday_Practices_for_Cultivating.jpg'},
            title: '50 Mindful Steps to Self Esteem',
            author: 'Janetti Marotta',
            filetype: 'pdf',
            document: {key: 'book/1650063214028_50_Mindful_Steps_to_Self_Esteem_Everyday_Practices_for_Cultivating.pdf', size: 1080000},
            isApproved: true,
        },
        {
            _id: JSON.parse('3'),
            image: {key: 'book-img/1650223337913_act like lady think like man.jpg'},
            title: 'Act like lady think like man.',
            author: 'Steve Harvey',
            filetype: 'pdf',
            document: {key: 'book/1650063214860_act like lady think like man.pdf', size: 2780000},
            isApproved: true,
        },
        {
            _id: JSON.parse('4'),
            image: {key: 'book-img/1650223048425_100 Ways to Simplify Your Life - Joyce Meyer.jpg'},
            title: '100 Ways to Simplify Your Life',
            author: 'Joyce Meyer',
            filetype: 'pdf',
            document: {key: 'book/1650063214134_100 Ways to Simplify Your Life - Joyce Meyer.pdf', size: 649000},
            isApproved: true,
        },
        {
            _id: JSON.parse('5'),
            image: {key: 'book-img/1650223030084_50_Mindful_Steps_to_Self_Esteem_Everyday_Practices_for_Cultivating.jpg'},
            title: '50 Mindful Steps to Self Esteem',
            author: 'Janetti Marotta',
            filetype: 'pdf',
            document: {key: 'book/1650063214028_50_Mindful_Steps_to_Self_Esteem_Everyday_Practices_for_Cultivating.pdf', size: 1080000},
            isApproved: true,
        },
        {
            _id: JSON.parse('6'),
            image: {key: 'book-img/1650223337913_act like lady think like man.jpg'},
            title: 'Act like lady think like man.',
            author: 'Steve Harvey',
            filetype: 'pdf',
            document: {key: 'book/1650063214860_act like lady think like man.pdf', size: 2780000},
            isApproved: true,
        },
        {
            _id: JSON.parse('7'),
            image: {key: 'book-img/1650223048425_100 Ways to Simplify Your Life - Joyce Meyer.jpg'},
            title: '100 Ways to Simplify Your Life',
            author: 'Joyce Meyer',
            filetype: 'pdf',
            document: {key: 'book/1650063214134_100 Ways to Simplify Your Life - Joyce Meyer.pdf', size: 649000},
            isApproved: true,
        },
        {
            _id: JSON.parse('8'),
            image: {key: 'book-img/1650223030084_50_Mindful_Steps_to_Self_Esteem_Everyday_Practices_for_Cultivating.jpg'},
            title: '50 Mindful Steps to Self Esteem',
            author: 'Janetti Marotta',
            filetype: 'pdf',
            document: {key: 'book/1650063214028_50_Mindful_Steps_to_Self_Esteem_Everyday_Practices_for_Cultivating.pdf', size: 1080000},
            isApproved: true,
        },
        {
            _id: JSON.parse('9'),
            image: {key: 'book-img/1650223337913_act like lady think like man.jpg'},
            title: 'Act like lady think like man.',
            author: 'Steve Harvey',
            filetype: 'pdf',
            document: {key: 'book/1650063214860_act like lady think like man.pdf', size: 2780000},
            isApproved: true,
        },
        {
            _id: JSON.parse('10'),
            image: {key: 'book-img/1650223048425_100 Ways to Simplify Your Life - Joyce Meyer.jpg'},
            title: '100 Ways to Simplify Your Life',
            author: 'Joyce Meyer',
            filetype: 'pdf',
            document: {key: 'book/1650063214134_100 Ways to Simplify Your Life - Joyce Meyer.pdf', size: 649000},
            isApproved: true,
        },
        {
            _id: JSON.parse('11'),
            image: {key: 'book-img/1650223030084_50_Mindful_Steps_to_Self_Esteem_Everyday_Practices_for_Cultivating.jpg'},
            title: '50 Mindful Steps to Self Esteem',
            author: 'Janetti Marotta',
            filetype: 'pdf',
            document: {key: 'book/1650063214028_50_Mindful_Steps_to_Self_Esteem_Everyday_Practices_for_Cultivating.pdf', size: 1080000},
            isApproved: true,
        },
        {
            _id: JSON.parse('12'),
            image: {key: 'book-img/1650223337913_act like lady think like man.jpg'},
            title: 'Act like lady think like man.',
            author: 'Steve Harvey',
            filetype: 'pdf',
            document: {key: 'book/1650063214860_act like lady think like man.pdf', size: 2780000},
            isApproved: true,
        },
        {
            _id: JSON.parse('13'),
            image: {key: 'book-img/1650223048425_100 Ways to Simplify Your Life - Joyce Meyer.jpg'},
            title: '100 Ways to Simplify Your Life',
            author: 'Joyce Meyer',
            filetype: 'pdf',
            document: {key: 'book/1650063214134_100 Ways to Simplify Your Life - Joyce Meyer.pdf', size: 649000},
            isApproved: true,
        },
        {
            _id: JSON.parse('14'),
            image: {key: 'book-img/1650223030084_50_Mindful_Steps_to_Self_Esteem_Everyday_Practices_for_Cultivating.jpg'},
            title: '50 Mindful Steps to Self Esteem',
            author: 'Janetti Marotta',
            filetype: 'pdf',
            document: {key: 'book/1650063214028_50_Mindful_Steps_to_Self_Esteem_Everyday_Practices_for_Cultivating.pdf', size: 1080000},
            isApproved: true,
        },
        {
            _id: JSON.parse('15'),
            image: {key: 'book-img/1650223337913_act like lady think like man.jpg'},
            title: 'Act like lady think like man.',
            author: 'Steve Harvey',
            filetype: 'pdf',
            document: {key: 'book/1650063214860_act like lady think like man.pdf', size: 2780000},
            isApproved: true,
        },
        {
            _id: JSON.parse('16'),
            image: {key: 'book-img/1650223048425_100 Ways to Simplify Your Life - Joyce Meyer.jpg'},
            title: '100 Ways to Simplify Your Life',
            author: 'Joyce Meyer',
            filetype: 'pdf',
            document: {key: 'book/1650063214134_100 Ways to Simplify Your Life - Joyce Meyer.pdf', size: 649000},
            isApproved: true,
        },
        {
            _id: JSON.parse('17'),
            image: {key: 'book-img/1650223030084_50_Mindful_Steps_to_Self_Esteem_Everyday_Practices_for_Cultivating.jpg'},
            title: '50 Mindful Steps to Self Esteem',
            author: 'Janetti Marotta',
            filetype: 'pdf',
            document: {key: 'book/1650063214028_50_Mindful_Steps_to_Self_Esteem_Everyday_Practices_for_Cultivating.pdf', size: 1080000},
            isApproved: true,
        },
        {
            _id: JSON.parse('18'),
            image: {key: 'book-img/1650223337913_act like lady think like man.jpg'},
            title: 'Act like lady think like man.',
            author: 'Steve Harvey',
            filetype: 'pdf',
            document: {key: 'book/1650063214860_act like lady think like man.pdf', size: 2780000},
            isApproved: true,
        },
        {
            _id: JSON.parse('19'),
            image: {key: 'book-img/1650223048425_100 Ways to Simplify Your Life - Joyce Meyer.jpg'},
            title: '100 Ways to Simplify Your Life',
            author: 'Joyce Meyer',
            filetype: 'pdf',
            document: {key: 'book/1650063214134_100 Ways to Simplify Your Life - Joyce Meyer.pdf', size: 649000},
            isApproved: true,
        },
        {
            _id: JSON.parse('20'),
            image: {key: 'book-img/1650223030084_50_Mindful_Steps_to_Self_Esteem_Everyday_Practices_for_Cultivating.jpg'},
            title: '50 Mindful Steps to Self Esteem',
            author: 'Janetti Marotta',
            filetype: 'pdf',
            document: {key: 'book/1650063214028_50_Mindful_Steps_to_Self_Esteem_Everyday_Practices_for_Cultivating.pdf', size: 1080000},
            isApproved: true,
        },
        {
            _id: JSON.parse('21'),
            image: {key: 'book-img/1650223337913_act like lady think like man.jpg'},
            title: 'Act like lady think like man.',
            author: 'Steve Harvey',
            filetype: 'pdf',
            document: {key: 'book/1650063214860_act like lady think like man.pdf', size: 2780000},
            isApproved: true,
        },
        {
            _id: JSON.parse('22'),
            image: {key: 'book-img/1650223048425_100 Ways to Simplify Your Life - Joyce Meyer.jpg'},
            title: '100 Ways to Simplify Your Life',
            author: 'Joyce Meyer',
            filetype: 'pdf',
            document: {key: 'book/1650063214134_100 Ways to Simplify Your Life - Joyce Meyer.pdf', size: 649000},
            isApproved: false,
        },
        {
            _id: JSON.parse('23'),
            image: {key: 'book-img/1650223030084_50_Mindful_Steps_to_Self_Esteem_Everyday_Practices_for_Cultivating.jpg'},
            title: '50 Mindful Steps to Self Esteem',
            author: 'Janetti Marotta',
            filetype: 'pdf',
            document: {key: 'book/1650063214028_50_Mindful_Steps_to_Self_Esteem_Everyday_Practices_for_Cultivating.pdf', size: 1080000},
            isApproved: false,
        },
        {
            _id: JSON.parse('24'),
            image: {key: 'book-img/1650223337913_act like lady think like man.jpg'},
            title: 'Act like lady think like man.',
            author: 'Steve Harvey',
            filetype: 'pdf',
            document: {key: 'book/1650063214860_act like lady think like man.pdf', size: 2780000},
            isApproved: false,
        },
    ],
    requests: [],
    users: []
}

export default FAKE_DATA